[package]
name = "wbor_studio_dashboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.5"
minreq = {version = "2.10.0", features = ["https"]}
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
