[package]
name = "wbor_studio_dashboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = {version = "0.34.5", features = ["image", "ttf"]}
minreq = {version = "2.10.0", features = ["https"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
derive-alias = {version = "0.1.0"}
